name: Build and deploy to IBM Cloud Functions

# Execute on every push to main
on:
  workflow_dispatch:
  push:
    branches:
      - ul-wip 

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_GROUP: Prometeo
  IBM_CLOUD_REGION: us-south
  IBM_CLOUD_API: ${{secrets.IBM_CLOUD_API_KEY}}
  IBM_CE_PROJECT_NAME: ${{secrets.IBM_CE_PROJECT_NAME}}

jobs:
  package-deploy-fn:
    name: Package and deploy an OpenWhisk action to IBM Cloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create pem file
        env:
          IOT_PEM_CERT: ${{ secrets.IOT_PEM_CERT }}
        run: |
          echo "$IOT_PEM_CERT" >> ./messaging.pem
          echo "running ls **"
          ls -lta .
          echo "finished running ls **"
      - name: Install IBM CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
        shell: bash
      - name: Install CE plugin
        run: ibmcloud plugin install code-engine
        shell: bash
      - name: Log into IBM Cloud
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_GROUP"
        shell: bash
      - name: List the project details
        run: ibmcloud ce project get -n $IBM_CE_PROJECT_NAME
        shell: bash
      - name: List the project details
        run: ibmcloud ce project get -n $IBM_CE_PROJECT_NAME
        continue-on-error: true
        shell: bash
      - name: Step 2
        run: echo ::set-output name=status::success
        continue-on-error: true
    
  